# Generated by Django 5.0.3 on 2024-03-18 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APPVAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstatus', models.TextField()),
                ('errmsg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GROUPS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('groupname', models.CharField(max_length=255, unique=True)),
                ('notification', models.BooleanField(default=True)),
                ('chat_id', models.EmailField(blank=True, max_length=100)),
                ('api_token', models.CharField(blank=True, max_length=255)),
                ('users', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('helpname', models.CharField(max_length=255, unique=True)),
                ('helpdesc', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('remindname', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=150)),
                ('reminddesc', models.CharField(max_length=150)),
                ('remindtype', models.CharField(max_length=10)),
                ('expiredate', models.DateTimeField(blank=True, null=True)),
                ('remindbefor', models.IntegerField(default=10)),
                ('groups', models.CharField(default=None, max_length=100, null=True)),
                ('remainingdays', models.CharField(max_length=100, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, null=True)),
                ('remindlog', models.TextField()),
                ('notification', models.BooleanField(default=True)),
                ('prev_alertstatus', models.BooleanField(default=False)),
                ('alertstatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=128, unique=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('phone', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('admin', models.CharField(default='user', max_length=15)),
                ('enable', models.BooleanField(default=True)),
                ('groups', models.TextField(default='')),
                ('loginstatus', models.BooleanField(default=False)),
                ('lastlogin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('task', models.TextField(unique=True)),
                ('taskhelp', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_018.help')),
            ],
        ),
        migrations.CreateModel(
            name='GROUPSREMIDES',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_018.groups')),
                ('remind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_018.reminder')),
            ],
        ),
        migrations.AddField(
            model_name='reminder',
            name='createby_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_018.users'),
        ),
        migrations.CreateModel(
            name='GROUPSUSERS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_018.groups')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_018.users')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTasksReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('report', models.TextField(default='')),
                ('reportdate', models.DateTimeField(blank=True, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, null=True)),
                ('createby', models.CharField(default=None, max_length=100)),
                ('createby_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_018.users')),
            ],
        ),
        migrations.CreateModel(
            name='USERSLOG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('log', models.TextField()),
                ('logdate', models.DateTimeField()),
                ('user_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_018.users')),
            ],
        ),
        migrations.CreateModel(
            name='UsersReportsShow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('report_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_018.dailytasksreport')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_018.users')),
            ],
        ),
    ]
